services:
  web:
    build: .
    ports:
      - "8080:80"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: diary_app_php
      DB_USER: root
      DB_PASSWORD: root
    depends_on:
      - db

  db:
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    ports:
      - "3307:3306"
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: diary_app_php
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
